/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import React, { useRef } from 'react'
import * as THREE from 'three'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader, GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    chocolate: THREE.Mesh
  }
  materials: {
    chocolate: THREE.MeshStandardMaterial
  }
}

export const Chocolate = (props: JSX.IntrinsicElements['group']) => {
  const group = useRef<THREE.Group>()

  const { nodes, materials } = useLoader<GLTFResult>(
    GLTFLoader,
    '3d/chocolate.gltf'
  )

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials.chocolate}
        geometry={nodes.chocolate.geometry}
      />
    </group>
  )
}
