/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader, GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    medalion: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
  }
}

export const Medalion = (props: JSX.IntrinsicElements['group']) => {
  const group = useRef<THREE.Group>()

  const { nodes, materials } = useLoader<GLTFResult>(
    GLTFLoader,
    '3d/medalion.gltf'
  )

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials['Material.001']}
        geometry={nodes.medalion.geometry}
        rotation={[0, 0, -0.17]}
      />
    </group>
  )
}
